apiVersion: game.game.yourdomain.com/v1
kind: GameEventScaleRule
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: gameeventscalerule-sample
spec:
  # TODO(user): Add fields here
