apiVersion: game.game.yourdomain.com/v1
kind: GameEventScaleRule
metadata:
  name: main-game-event-scaler # name of the game event scaler
  namespace: default            # namespace of the game event scaler
spec:
  eventEndpointURL: "http://game-event-api.default.svc.cluster.local/api/events"
  pollingInterval: "61s" # poll the event endpoint every 61 seconds
  rules:
    - eventType: "MassPvPEvent"
      targetMicroservice: "pvp-battle-service" # deployment name for scaling
      desiredReplicas: 20                       # Desired number of replicas during the event
      preScaleMinutes: 1                        # Start scaling 1 minute before the event
      postScaleMinutes: 10                      # Scale down replicas after 10 minutes after the event
      defaultReplicas: 2                        # Number of replicas after the event

    - eventType: "RaidBossSpawn"
      targetMicroservice: "raid-instance-manager"
      desiredReplicas: 15
      preScaleMinutes: 3
      postScaleMinutes: 5
      defaultReplicas: 2